---
- hosts: all
  remote_user: root

  tasks:
    - name: Ensure /etc/hosts exists and mode=0644
      file: path=/etc/hosts mode=0644 state=file

    - name: Ensure /etc/hostname exists and mode=0644
      file: path=/etc/hostname mode=0644 state=file

    - name: Ensure media user exists
      user: name=media comment="Media User" uid=20000 shell=/bin/bash generate_ssh_key=yes

    - name: Ensure user belongs to group
      user: user=media groups=projectx append=yes

- hosts: all:!linuxcbtbuild1
  remote_user: root

  tasks:
    - name: Ensure Time is SYNCHED using ntpdate
      shell: ntpdate 192.168.0.201

- hosts: redhat
  remote_user: root

  tasks:
    - name: Check if SELinux is set to ENFORCING on redhat systems
      selinux: policy=targeted state=enforcing
