---
- hosts: all
  remote_user: root

  tasks:
    - name: Update APT
      apt: update_cache=yes
      when: ansible_os_family == "Debian"

    - name: Update Packages
      apt: upgrade=yes
      when: ansible_os_family == "Debian"

    - name: Update YUM
      yum: name=* state=latest
      when: ansible_os_family == "RedHat"
